#cloud-config
package_update: true
packages:
  - docker.io
  - curl
  - git
  - python3-pip

runcmd:
  - echo "Starting GitHub Runner installation..."
  - mkdir -p /actions-runner && cd /actions-runner
  - curl -o actions-runner-linux-x64-2.316.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.316.1/actions-runner-linux-x64-2.316.1.tar.gz
  - tar xzf ./actions-runner-linux-x64-2.316.1.tar.gz
  - export RUNNER_ALLOW_RUNASROOT="1"
  - ./config.sh --url $REPO_URL --token $REG_TOKEN --unattended --replace --labels self-hosted
  - ./svc.sh install
  - ./svc.sh start
  - echo "GitHub Runner is active."